-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alembic_version
(
    version_num character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS public.equipos
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ciudad character varying(100) COLLATE pg_catalog."default" NOT NULL,
    entrenador character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT equipos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estadisticas
(
    id serial NOT NULL,
    jugador_id integer NOT NULL,
    partido_id integer NOT NULL,
    turnos_bateo integer NOT NULL,
    hits integer NOT NULL,
    dobles integer NOT NULL,
    triples integer NOT NULL,
    home_runs integer NOT NULL,
    carreras_anotadas integer NOT NULL,
    carreras_impulsadas integer NOT NULL,
    bases_por_bola integer NOT NULL,
    ponches integer NOT NULL,
    promedio_bateo double precision NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT estadisticas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.jugadores
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date NOT NULL,
    posicion character varying(20) COLLATE pg_catalog."default" NOT NULL,
    numero integer NOT NULL,
    equipo_id integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT jugadores_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.partidos
(
    id serial NOT NULL,
    torneo_id integer NOT NULL,
    equipo_local_id integer NOT NULL,
    equipo_visitante_id integer NOT NULL,
    fecha timestamp without time zone NOT NULL,
    ubicacion character varying(200) COLLATE pg_catalog."default" NOT NULL,
    resultado_local integer,
    resultado_visitante integer,
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT partidos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.torneos
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone NOT NULL,
    ubicacion character varying(200) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT torneos_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.estadisticas
    ADD CONSTRAINT estadisticas_jugador_id_fkey FOREIGN KEY (jugador_id)
    REFERENCES public.jugadores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estadisticas
    ADD CONSTRAINT estadisticas_partido_id_fkey FOREIGN KEY (partido_id)
    REFERENCES public.partidos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.jugadores
    ADD CONSTRAINT jugadores_equipo_id_fkey FOREIGN KEY (equipo_id)
    REFERENCES public.equipos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.partidos
    ADD CONSTRAINT partidos_equipo_local_id_fkey FOREIGN KEY (equipo_local_id)
    REFERENCES public.equipos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.partidos
    ADD CONSTRAINT partidos_equipo_visitante_id_fkey FOREIGN KEY (equipo_visitante_id)
    REFERENCES public.equipos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.partidos
    ADD CONSTRAINT partidos_torneo_id_fkey FOREIGN KEY (torneo_id)
    REFERENCES public.torneos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;