"""Simplificacion de tablas

Revision ID: 97eeaf9dd32e
Revises: 86c21d7993b9
Create Date: 2025-06-13 21:38:34.668450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97eeaf9dd32e'
down_revision: Union[str, None] = '86c21d7993b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipos', 'estado')
    op.drop_column('equipos', 'categoria')
    op.drop_column('equipos', 'division')
    op.drop_column('equipos', 'email_contacto')
    op.drop_column('equipos', 'telefono_contacto')
    op.drop_column('jugadores', 'email')
    op.drop_column('jugadores', 'telefono')
    op.drop_column('partidos', 'estado')
    op.drop_column('torneos', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torneos', sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('partidos', sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('jugadores', sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('jugadores', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('equipos', sa.Column('telefono_contacto', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('equipos', sa.Column('email_contacto', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('equipos', sa.Column('division', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('equipos', sa.Column('categoria', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('equipos', sa.Column('estado', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
